### LIST developers

GET    http://localhost:3000/developers

### CREATE developer

POST   http://localhost:3000/developers
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@gmail.com",
    "dateOfBirth": "1990-01-01"
}

### UPDATE developer

PATCH http://localhost:3000/developers/dev_ewpWRbThMqi0KxSO8EC83
Content-Type: application/json

{
    "email": "teste@acme.com"
}
### DELETE developer

DELETE http://localhost:3000/developers/dev_ewpWRbThMqi0KxSO8EC83